### ISSUE TITLE
미숙 드리머 가사 싱크

### ISSUE THREAD

**Issue by contactn** [So-chiru/LLCT#105]
**곡명 혹은 ID**
어느 곡의 콜표를 작업 하셨는지 알려주세요.
미숙 드리머 , 10016
**콜표 타입**
사이트에 사용하는 JSON 파일인지, 이미지인지, 텍스트인지 입력해 주세요.
JSON파일 
**기타 내용**
관리자에게 말하고 싶은 내용이나 설명이 있다면 입력해 주세요.
콜 & 리스폰스 들어간 곡들을 제가 아직 잘 몰라서 콜이 없는 곡먼저 해봤습니다 ㅎ..
**콜표 내용**
콜표 이미지나 텍스트 혹은 JSON 파일을 입력하거나 올려주세요. 이미지인 경우 3505 x 2480 사이즈의 jpg로 올려주시면 감사하겠습니다.
[10016.zip](https://github.com/So-chiru/LLCT/files/3775623/10016.zip)

**Comment by contactn** [comment]
앗 혹시 멤버 파트별로 색상을 나눠야되나요?

**Comment by So-chiru** [comment]
꼭 나누실 필요는 없어요 나눠지는거는 효과로 들어가는거라서.. ㅎ

**Comment by contactn** [comment]
아 효과군요 알겠습니다
