### ISSUE TITLE
Awaken the power

### ISSUE THREAD

**Issue by contactn** [So-chiru/LLCT#106]
**곡명 혹은 ID**
어느 곡의 콜표를 작업 하셨는지 알려주세요.
Awaken the power , 10037
**콜표 타입**
사이트에 사용하는 JSON 파일인지, 이미지인지, 텍스트인지 입력해 주세요.
JSON 압축 파일
**기타 내용**
관리자에게 말하고 싶은 내용이나 설명이 있다면 입력해 주세요.
콜 & 리스폰스 들어간 곡을 처음해봤는데 틀린부분이있다면 말씀해주세요 수정하겟습니다
**콜표 내용**
콜표 이미지나 텍스트 혹은 JSON 파일을 입력하거나 올려주세요. 이미지인 경우 3505 x 2480 사이즈의 jpg로 올려주시면 감사하겠습니다.
[10037.zip](https://github.com/So-chiru/LLCT/files/3775756/10037.zip)

**Comment by So-chiru** [comment]
가뭄인 콜표에 콜표 깔끔하게 정리 해 주셔서 감사드립니다! ㅠ 그리고 혹시나 다음부터는 이 부분은 기능을 사용해서 작성해 주시면 굳이 색상 안 정하고도 알아서 지정이 되기 때문에 팁 몇가지 드리자면

<img width="654" alt="Screen Shot 2019-10-29 at 7 03 30 PM" src="https://user-images.githubusercontent.com/32066651/67757297-e36e7100-fa7e-11e9-8d6e-34d2b2217daa.png">

이 부분은

<img width="358" alt="Screen Shot 2019-10-29 at 7 03 43 PM" src="https://user-images.githubusercontent.com/32066651/67757433-24ff1c00-fa7f-11e9-9a10-98e42938f0f7.png">

종류를 4로 해 주시면

<img width="358" alt="Screen Shot 2019-10-29 at 7 03 52 PM" src="https://user-images.githubusercontent.com/32066651/67757453-2c262a00-fa7f-11e9-9d60-3610a263521c.png">

이런식으로 따라 부르는 텍스트가 지정이 됩니다! 이러면 굳이 색상 설정을 할 필요가 없어집니다.
마찬가지로 2번으로 설정 해 주시면 아래와 같이 틱 소리를 낼 수 있게 해주는 콜 텍스트가 지정됩니다. 

<img width="358" alt="Screen Shot 2019-10-29 at 7 03 57 PM" src="https://user-images.githubusercontent.com/32066651/67757491-3fd19080-fa7f-11e9-86aa-c29faac4f561.png">


그리고 간주 부분의 < 하이 > 부분은 예전에는 하이를 반복해서 길게 썼는데 불편해서 다음과 같이 줄일 수 있게 추가 했었어요

<img width="358" alt="Screen Shot 2019-10-29 at 7 08 50 PM" src="https://user-images.githubusercontent.com/32066651/67757652-8fb05780-fa7f-11e9-8960-5c80bf9a2ce8.png">

이 하이 부분만 선택 해 주신 후

<img width="436" alt="Screen Shot 2019-10-29 at 7 09 42 PM" src="https://user-images.githubusercontent.com/32066651/67757718-aeaee980-fa7f-11e9-92c2-8ca404f62089.png">

반복 딜레이를 설정 해 주시면 자동으로 끝 지점까지 반복시켜 줍니다

딜레이 값을 찾는 방법은 화면 오른쪽 위의 시간 부분에 [xxxxx] 이런 식으로 된게 타임코드인데
첫번째 하이 시간과 두번째 하이가 들어가는 시간의 차이를 내주시면 딜레이 값이 나옵니다!

대부분 60~80 정도 딜레이가 있기 때문에 70으로 먼저 맞춰주시고 느린 감이 있으면 딜레이를 줄이고 빠른 감이면 딜레이를 늘리는 형식으로 적절값을 찾아 주시면 감사하겠습니다..

그리고 귀한 시간 내 주셔서 만들어 주셔서 감사드립니다..!

**Comment by So-chiru** [comment]
그리고 질문 사항 있으시면 언제든지 이슈 남겨주시길 바랍니다!

**Comment by contactn** [comment]
아하 좋은 팁 감사합니다. 간주부분에 가사등록되있는거 보니까 20번 으로 되있길래 20번써놧는데 줄일수 있었군요. 유용히 사용하도록하겠습니다 ㅎㅎ
