### ISSUE TITLE
밤하늘은 뭐든지 알고있어 가사 싱크

### ISSUE THREAD

**Issue by contactn** [So-chiru/LLCT#107]
**곡명 혹은 ID**
어느 곡의 콜표를 작업 하셨는지 알려주세요.
밤하늘은 뭐든지 알고있어 , 10047
**콜표 타입**
사이트에 사용하는 JSON 파일인지, 이미지인지, 텍스트인지 입력해 주세요.
JSON 압축 파일
**기타 내용**
관리자에게 말하고 싶은 내용이나 설명이 있다면 입력해 주세요.

**콜표 내용**
콜표 이미지나 텍스트 혹은 JSON 파일을 입력하거나 올려주세요. 이미지인 경우 3505 x 2480 사이즈의 jpg로 올려주시면 감사하겠습니다.
[10047.zip](https://github.com/So-chiru/LLCT/files/3783813/10047.zip)

**Comment by So-chiru** [comment]
![icon_9](https://user-images.githubusercontent.com/32066651/67839996-41ab5a80-fb38-11e9-9081-d75a7e6dc4d8.gif)

감사합니다..!
