### ISSUE TITLE
元気全開 DAY! DAY! DAY! 가사 싱크 콜&리스폰스 표

### ISSUE THREAD

**Issue by contactn** [So-chiru/LLCT#108]
**곡명 혹은 ID**
어느 곡의 콜표를 작업 하셨는지 알려주세요.
元気全開 DAY! DAY! DAY! , 10046
**콜표 타입**
사이트에 사용하는 JSON 파일인지, 이미지인지, 텍스트인지 입력해 주세요.
JSON 압축 파일
**기타 내용**
관리자에게 말하고 싶은 내용이나 설명이 있다면 입력해 주세요.
1. 2:17초 부분의 음원에는 콘치와! 라고 콜이 들어가있지만 정식 콜&리스폰스 표에는 콘치카! 라고 써있기때문에 정식 콜&리스폰스 표를 차용했습니다
2. 간주부분의 "We are CYaRon! - I love CYaRon!" 은 아쿠아 퍼스트 라이브 'Step! ZERO to ONE!!' 의 콜&리스폰스 를 보고 타이밍에 맞춰서 작성했습니다.

**콜표 내용**
콜표 이미지나 텍스트 혹은 JSON 파일을 입력하거나 올려주세요. 이미지인 경우 3505 x 2480 사이즈의 jpg로 올려주시면 감사하겠습니다.
[10046.zip](https://github.com/So-chiru/LLCT/files/3789966/10046.zip)

**Comment by So-chiru** [comment]
삐기이이이잇 센스 ㅋㅋㅋㅋ 오늘도 수고해 주셔서 감사합니다!

그리고 
<img width="434" alt="Screen Shot 2019-10-31 at 11 25 48 PM" src="https://user-images.githubusercontent.com/32066651/67955335-c9c35a00-fc35-11e9-8567-e6dea6dcd1e1.png">

이 부분은 반복 적용 되었을때 좀 어색한 감 있어서 그냥 따로 분리하는 편이 좋을거 같아서 분리했습니다..

**Comment by So-chiru** [comment]
아 가사에 오른쪽 클릭에도 기능 있어요

<img width="845" alt="Screen Shot 2019-10-31 at 11 31 28 PM" src="https://user-images.githubusercontent.com/32066651/67955872-946b3c00-fc36-11e9-8196-c0f6192904fe.png">

ㄷㄷ;;

**Comment by contactn** [comment]
아 젠장 저런기능 있는지도 모르고 항상 싱크맞추다가 틀린부분 발견하면 현타오는거 부여잡고 처음부터 다시했는뎈ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ

**Comment by contactn** [comment]
ㅠㅠㅠ ㅋㅋㅋㅋ 좋은 팁, 버그 현상 항상 감사합니다
