### ISSUE TITLE
Strawberry Trapper 가사 싱크, 콜&리스폰스 표

### ISSUE THREAD

**Issue by contactn** [So-chiru/LLCT#110]
**곡명 혹은 ID**
어느 곡의 콜표를 작업 하셨는지 알려주세요.
Strawberry Trapper , 10058
**콜표 타입**
사이트에 사용하는 JSON 파일인지, 이미지인지, 텍스트인지 입력해 주세요.
JSON 압축파일
**기타 내용**
관리자에게 말하고 싶은 내용이나 설명이 있다면 입력해 주세요.

**콜표 내용**
콜표 이미지나 텍스트 혹은 JSON 파일을 입력하거나 올려주세요. 이미지인 경우 3505 x 2480 사이즈의 jpg로 올려주시면 감사하겠습니다.
[10058.zip](https://github.com/So-chiru/LLCT/files/3794975/10058.zip)

**Comment by So-chiru** [comment]
![image](https://user-images.githubusercontent.com/32066651/68032768-b8478400-fd01-11e9-98c8-92e6bf540d56.png)

기여 감사합니다...
