### ISSUE TITLE
콜표 제작 사이트가 막혔나요?

### ISSUE THREAD

**Issue by contactn** [So-chiru/LLCT#116]
**버그 설명**
버그를 정확히 설명 해 주시면 빠른 파악이 가능합니다.
The page could not be found. 라는 문구가 뜨면서 접속이 안됩니다.. 드라이브 포맷하고 와서 함 접속해봤는데 안되네요.
**재현 방법**
다음 방법을 통해 재현이 가능합니다.
1. '...' 아이콘 클릭
2. '...' 버튼 클릭
3. 버그 발견

**원래 예상된 기능**
버그가 없었다면 원래 보여질 기능에 대해서 아시면 설명 해주세요.

**스크린샷**
스크린샷이 있다면 올려주세요.
![캡처](https://user-images.githubusercontent.com/57008083/68534597-9db48100-0379-11ea-9ff1-9aa2948a3498.PNG)

**브라우저 버전:**
 - 기기: [예시: iPhone XS Max, PC]
 - OS: [예시: iOS13.0, Windows 10]
 - 브라우저 [예시: Chrome, Safari]
 - 브라우저 버전 [예시: 13 (Safari인 경우 OS 버전)]
크롬 브라우저 입니다. (아마.. 64?)
**기타 내용**
기타 내용이 있다면 적어주세요.

**Comment by So-chiru** [comment]
`https://lovelivec.kr/editor?id=` 가 아니라  `https://lovelivec.kr/editor.html?id=~~~` 처럼 editor 뒤에 .html 붙여주셔야 합니다

**Comment by contactn** [comment]
아..? 포맷하기 전만해도 저렇게 잘썻는데.. 음... 일단알겠습니다 감사합니다
