### ISSUE TITLE
スリリング·ワンウェイ 가사 싱크  콜&리스폰스 표

### ISSUE THREAD

**Issue by contactn** [So-chiru/LLCT#117]
**곡명 혹은 ID**
어느 곡의 콜표를 작업 하셨는지 알려주세요.
スリリング·ワンウェイ , 10026
**콜표 타입**
사이트에 사용하는 JSON 파일인지, 이미지인지, 텍스트인지 입력해 주세요.
JSON 압축 파일
**기타 내용**
관리자에게 말하고 싶은 내용이나 설명이 있다면 입력해 주세요.
혹시 콜표 업로드 하실때 가사 싱크같은거 수정하시고 올리시나요??
**콜표 내용**
콜표 이미지나 텍스트 혹은 JSON 파일을 입력하거나 올려주세요. 이미지인 경우 3505 x 2480 사이즈의 jpg로 올려주시면 감사하겠습니다.
[10026.zip](https://github.com/So-chiru/LLCT/files/3831326/10026.zip)

**Comment by So-chiru** [comment]
```
혹시 콜표 업로드 하실때 가사 싱크같은거 수정하시고 올리시나요??
```

바뀐 콜이 있거나 기타 싱크 성능 때문에 수정해서 올리는 부분도 있습니다.. 👀

**Comment by contactn** [comment]
아하 알겠습니다

**Comment by So-chiru** [comment]
점점 싱크가 거의 원곡 하고 같아지네요 ㄷㄷ...
노력해 주시는데 드리는 건 없어서 죄송합니다... ㅠㅠㅠ
