### ISSUE TITLE
MY舞☆ TONIGHT 가사 싱크 , 콜&리스폰스 표

### ISSUE THREAD

**Issue by contactn** [So-chiru/LLCT#121]
**곡명 혹은 ID**
어느 곡의 콜표를 작업 하셨는지 알려주세요.
MY舞☆ TONIGHT , 10035
**콜표 타입**
사이트에 사용하는 JSON 파일인지, 이미지인지, 텍스트인지 입력해 주세요.
JSON 압축 파일
**기타 내용**
관리자에게 말하고 싶은 내용이나 설명이 있다면 입력해 주세요.

**콜표 내용**
콜표 이미지나 텍스트 혹은 JSON 파일을 입력하거나 올려주세요. 이미지인 경우 3505 x 2480 사이즈의 jpg로 올려주시면 감사하겠습니다.
[10035.zip](https://github.com/So-chiru/LLCT/files/3859565/10035.zip)

**Comment by contactn** [comment]
MY 마이 에 ☆ 때셨네요.. 제목따라서 넣은건데 ㅋㅋㅋㅋ

**Comment by So-chiru** [comment]
특수 문자 같은 경우에는 letter-spacing 효과가 과하게 들어가는 경향이 있어서 땠습니다.. 양해 부탁드립니다

**Comment by contactn** [comment]
기술적으로 문제가된다면 언제든지 수정하셔도 됩니다. 혹시 다른 기술적으로 힘든게 있다면 알려주세요. 반영해서 만들겠습니다
