### ISSUE TITLE
Daydream Warrior 가사 싱크, 콜&리스폰스 표

### ISSUE THREAD

**Issue by contactn** [So-chiru/LLCT#123]
**곡명 혹은 ID**
어느 곡의 콜표를 작업 하셨는지 알려주세요.
Daydream Warrior , 10024
**콜표 타입**
사이트에 사용하는 JSON 파일인지, 이미지인지, 텍스트인지 입력해 주세요.
JSON 압축 파일
**기타 내용**
관리자에게 말하고 싶은 내용이나 설명이 있다면 입력해 주세요.
오랜만에 돌아왔습니다. 한동안 귀찮기도하고 유닛, 솔로, 듀오, 콜표가 없는 신곡들을 제외한 대부분의 아쿠아 곡들을 작업했기때문에 어느정도 손을 놨었습니다만, 곧 1달뒤면 페스가 다가오기때문에 그에 맞춰서 다시 작업하기 시작했습니다. 아쿠아는 대부분 작업이 되어있기 때문에 슬슬 뮤즈곡을 작성할까 생각중입니다. 물론 작업이 안된 아쿠아 곡도 가끔씩 할 예정입니다. 물붕이의 부족한 실력입니다만 앞으로도 잘부탁드립니다.
**콜표 내용**
콜표 이미지나 텍스트 혹은 JSON 파일을 입력하거나 올려주세요. 이미지인 경우 3505 x 2480 사이즈의 jpg로 올려주시면 감사하겠습니다.
[10024.zip](https://github.com/So-chiru/LLCT/files/3965019/10024.zip)

**Comment by So-chiru** [comment]
ㅠㅠㅠ 시간 남아도실때 편하게 해주십쇼.. 앞으로도 잘 부탁드립니다!

**Comment by contactn** [comment]
앞으로는 곧 방학이고 시간도 남을것이기 때문에 ㅋㅋㅋ
