### ISSUE TITLE
Pops Heartで踊るんだもん！ 가사 싱크, 콜&리스폰스 표 

### ISSUE THREAD

**Issue by contactn** [So-chiru/LLCT#124]
**곡명 혹은 ID**
어느 곡의 콜표를 작업 하셨는지 알려주세요.
Pops Heartで踊るんだもん！ , 10017
**콜표 타입**
사이트에 사용하는 JSON 파일인지, 이미지인지, 텍스트인지 입력해 주세요.
JSON 압축 파일
**기타 내용**
관리자에게 말하고 싶은 내용이나 설명이 있다면 입력해 주세요.
이거 가사안에 파란색 콜은 뭘 뜻하는거죠? 초록색콜은 대충 알겠는데.. 
**콜표 내용**
콜표 이미지나 텍스트 혹은 JSON 파일을 입력하거나 올려주세요. 이미지인 경우 3505 x 2480 사이즈의 jpg로 올려주시면 감사하겠습니다.
[10017.zip](https://github.com/So-chiru/LLCT/files/3987660/10017.zip)

**Comment by contactn** [comment]
아 그리고 뮤즈 콜표가 없는것들이 꽤나 많던데 그런것들은 갤러분이 올리신 콜표 써서 작성해도 될까요?

**Comment by So-chiru** [comment]
@contactn 네, 콜은 보편적인 걸 사용하니 갤 콜표나 https://lovelivecall.com 에서도 참고하셔도 좋습니다

**Comment by So-chiru** [comment]
아니면 #103 에 있는것도 좋을 것 같아요

**Comment by contactn** [comment]
네 알겠습니다
