### ISSUE TITLE
No brand girls 가사 싱크 , 콜&리스폰스 표

### ISSUE THREAD

**Issue by contactn** [So-chiru/LLCT#125]
**곡명 혹은 ID**
어느 곡의 콜표를 작업 하셨는지 알려주세요.
No brand girls , 00043
**콜표 타입**
사이트에 사용하는 JSON 파일인지, 이미지인지, 텍스트인지 입력해 주세요.
JSON 압축 파일
**기타 내용**
관리자에게 말하고 싶은 내용이나 설명이 있다면 입력해 주세요.
수정하실때 말씀해주세요 어느부분 수정해야되고 뭐가 틀렸고를 말씀해주시면 고쳐서 재 업로드 하겠습니다
**콜표 내용**
콜표 이미지나 텍스트 혹은 JSON 파일을 입력하거나 올려주세요. 이미지인 경우 3505 x 2480 사이즈의 jpg로 올려주시면 감사하겠습니다.
[00043.zip](https://github.com/So-chiru/LLCT/files/4000617/00043.zip)

**Comment by So-chiru** [comment]
수고 해 주셔서 수정은 제가 할려 했는데ㅠㅠ 다음부터는 이렇게 해 주시면 감사하겠습니다..

![image](https://user-images.githubusercontent.com/32066651/71518704-6aad5900-28f7-11ea-9c33-1a5370ef3e2f.png)

이렇게 가사가 아닌 부분은 종류가 "**3**" 입니다. 콜표에서는 색 차이가 별로 안나서 안보이는데 나중에 기능 구현 때문에 구분이 필요할 수 있으니 바꿔주세요!

![image](https://user-images.githubusercontent.com/32066651/71518759-b102b800-28f7-11ea-9a70-fcbe614cecb8.png)

일단 파란색과 초록색은 콜인데 차이점이 있다면 파란색은 노래에 있는 가사를 팬들이 따라하는 것인 방면, 초록색은 가사에는 없는 콜입니다.

저 부분에서는 [lovelivecall.com](lovelivecall.com) 사이트에서는 Hi로 다 통일이 되어있는데 노래에서는 구분되어 있으니 햇갈리지 않도록 저렇게 표시해 주셨으면 감사하겠습니다!

![image](https://user-images.githubusercontent.com/32066651/71518893-71889b80-28f8-11ea-8b0e-59b7fbba0bc8.png)

영어 가사는 많이 해보셨다시피 자동으로 칸을 뛰었을 때 Y e s, 처럼 다 분리가 되는데 Yes 처럼 발음 시간이 짧은 것들은 싱크 맞추기도 성가시니 Yes로 적어주시면 됩니다..

----

지금부터는 콜법관 입니다...

![image](https://user-images.githubusercontent.com/32066651/71519305-5f0f6180-28fa-11ea-9c3d-0c6d6758062a.png)

뮤즈 5th 라이브 기준으로 윗 하이 6번 들어가는 부분은 없습니다. 대신 뒤에 엇박은 들어갑니다 (거의 모든 럽라곡은 성우 유도가 없는 한 하이 콜 틱이 100을 넘어가지 않습니다)

----

수정 사항이 많네요ㅠ 귀한 시간 내주셔서 하는 작업이니 제가 수정해드릴테니 기본 틀만 작업 해 주셔도 됩니다 ㅠㅠ 항상 감사합니다..

**Comment by contactn** [comment]
아하 알겠습니다 3번도 있는지 몰랐네요 간주 초반부분은 넣으면 재밋을것같아서 넣어봣는데 ㅋㅋㅋ 다음부터는 조심해서 만들겠습니다 항상 수고하십니다 ㅎㅎ
