### ISSUE TITLE
Wonderful Rush 가사 싱크 , 콜&리스폰스 표

### ISSUE THREAD

**Issue by contactn** [So-chiru/LLCT#126]
**곡명 혹은 ID**
어느 곡의 콜표를 작업 하셨는지 알려주세요.
Wonderful Rush , 00032
**기타 내용**
관리자에게 말하고 싶은 내용이나 설명이 있다면 입력해 주세요.

**콜표 내용**
콜표 이미지나 텍스트 혹은 JSON 파일을 압축하여 올려주세요. 이미지인 경우 3232 x 2100 사이즈의 png로 올려주시면 감사하겠습니다.
[00032.zip](https://github.com/So-chiru/LLCT/files/4005865/00032.zip)

**Comment by So-chiru** [comment]
귀차니즘 때문에 늦어서 죄송하고 귀찮게 해드려서 죄송합니다 ㅠ

![image](https://user-images.githubusercontent.com/32066651/71667679-7d1d0c00-2da9-11ea-8ae6-d051d1c99344.png)

이 부분에서 `<` 는 쓰지않고 `(` 를 씁니다. `< 간주 부분 : ~~~ >` 처럼 어떤 주석이 들어가 있는 경우는 `<` 를 쓰는데 콜은 `(`로 통일하여 작성합니다

![image](https://user-images.githubusercontent.com/32066651/71667768-d8e79500-2da9-11ea-855f-fc4df80b9c82.png)

이 부분에서 `*`는 다음 경우가 아닌 경우에 쓰입니다.

1. 가사 줄의 시작 부분이 아님
2. 우- 하이! 뒤에 엇박 (하이) 콜의 시작 부분 [곡 타이밍을 맞추기 어려우면 추가]
3. 누가 봐도 여기에서 시작된다는 것을 인지할 수 있는 경우 (2번의 경우)

그리고 저렇게 하나의 단어로 표시 해두셨는데 그러지 않으시고도 루비 텍스트를 사용해서

![image](https://user-images.githubusercontent.com/32066651/71668002-a9855800-2daa-11ea-9ddc-ad843cdc49a6.png)

![image](https://user-images.githubusercontent.com/32066651/71667973-8d81b680-2daa-11ea-9e3b-47b092b7aba3.png)

저렇게 해두실 수 있습니다

그리고 * 다음에는 띄어쓰기 지켜 주십쇼 ㅠㅠ 안그러면

![image](https://user-images.githubusercontent.com/32066651/71668048-cb7eda80-2daa-11ea-86be-f55f231345db.png)

저렇게 보입니다 ㅠㅠ

![image](https://user-images.githubusercontent.com/32066651/71668470-64fabc00-2dac-11ea-9255-d7b1e0238c97.png)

그리고 하이는 간주 부분 하이만 `x 반복`을 쓰고
가사 중간에 엇박 넣는 경우는 `(하이 하이 하이 하이)` 처럼 전부 풀어서 써주세요

그리고 

`< 간주 부분 : 하이 x (반복)>` 처럼 특수 문자가 서로 붙는 경우에는 붙여씁니다.

---

그냥 귀찮으시면 나두면 제가 하겠습니다 ㅎㅎ 항상 수고 해 주셔서 감사합니다!

**Comment by So-chiru** [comment]
콜표 최장 110줄 넘어가는데 수고 하셨습니다 ㅠㅠ

**Comment by contactn** [comment]
아 ㅋㅋㅋ 죄송합니다 제가 루비 텍스쳐를 쓸줄 몰라서 소치루님이 수정하실때 보기 편하게 할려고 저렇게 별표를 쳐놧는데 일거리만 늘렸네요 ㅋㅋㅋㅋ 작업할때 유용히 쓰도록하겠습니다 ㅎㅎ 수고하세요!
