### ISSUE TITLE
それは僕たちの奇跡 가사 싱크 , 콜&리스폰스 표

### ISSUE THREAD

**Issue by contactn** [So-chiru/LLCT#127]
**곡명 혹은 ID**
어느 곡의 콜표를 작업 하셨는지 알려주세요.
それは僕たちの奇跡 , 00055
**기타 내용**
관리자에게 말하고 싶은 내용이나 설명이 있다면 입력해 주세요.

**콜표 내용**
콜표 이미지나 텍스트 혹은 JSON 파일을 압축하여 올려주세요. 이미지인 경우 3232 x 2100 사이즈의 png로 올려주시면 감사하겠습니다.
[00055.zip](https://github.com/So-chiru/LLCT/files/4058217/00055.zip)

**Comment by So-chiru** [comment]
항상 수고해주셔서 감사합니다! 콜 부분에서 교정해드릴 부분이 있다면

![image](https://user-images.githubusercontent.com/32066651/72345650-a3cb3300-3717-11ea-929e-fe08fba6043b.png)

저 부분은 아쿠아, 뮤즈, 기타 다른 오타쿠 라이브에서도 항상 쓰이는 부분이라 패턴이 **항상** 같습니다.

![image](https://user-images.githubusercontent.com/32066651/72345619-90b86300-3717-11ea-8682-f14000833b2f.png)

비트에 맞추실 필요는 없고 위처럼 하시면 됩니다

![image](https://user-images.githubusercontent.com/32066651/72345962-4683b180-3718-11ea-8ddd-4ab1b2c5c1ea.png)

2절의 여기는 우- 하이가 총 8번 들어갑니다.
그리고 그 다음 줄에서 바로 엇박 (하이) 8번 들어갑니다

그외에는 파이널 BD에 맞춰서 수정해뒀으니 자세한 사항은 커밋 참조해주시면 됩니다!

감사합니다!

**Comment by contactn** [comment]
아하 알겠습니다 콜표에  있는 그대로 옮겨놓다보니 잘 모르는게 많이 있네요 ㅎㅎ..
