### ISSUE TITLE
안녕하세요

### ISSUE THREAD

**Issue by Lacheln1** [So-chiru/LLCT#128]
깃허브 배워보고 싶다던 물붕이 입니다

**Comment by So-chiru** [comment]
일단 시작하기 전에 처음 하실 경우엔 오래 걸릴 수 있다는 점 알려드립니다..
한 곡 하시고 때려치셔도 감사할 따름입니다 ㅠ

깃허브에서 곡을 수정하는게 아니라 수정한 곡을 Github에 업로드하여 사이트에 올리는 방식입니다.

일단 곡 편집기 링크는 다음과 같습니다.

```
https://lovelivec.kr/editor.html?id=
```

?id= 뒤에 ID가 붙는 형식인데 ID는 사이트에서 노래를 불러왔을 때 ?pid= 뒤에 붙는 5자리 숫자를 입력하시면 됩니다.

ex) WILD STAR : 

![image](https://user-images.githubusercontent.com/32066651/72497534-151df980-3870-11ea-94eb-ac355d3d60d5.png)

https://lovelivec.kr/editor.html?id=00037

저렇게 링크에 들어가셨다면 편집기로 들어갑니다. UI를 설명해드리자면

![image](https://user-images.githubusercontent.com/32066651/72498117-bfe2e780-3871-11ea-99ae-75b09d2d5737.png)

처음에 작업할때는 건드리실 건 없고 페이지 오른쪽 위의 **timeline** 탭에 들어가주세요

![image](https://user-images.githubusercontent.com/32066651/72498685-4f3cca80-3873-11ea-98c8-c2c6a1fd57ea.png)


가사를 작성하실때 조심하셔야 할 부분이 띄어쓰기의 구분이 다르다는 점인데
흔히 쓰는 띄어쓰기 " " 를 하려면 띄어쓰기를 2번 하셔야 그게 띄어쓰기 처리됩니다. "  "
반대로 한번 하시게 되면 음절을 구분하는 요소로 쓰입니다.

예를 들어서 꿈의 문의 콜을 다음과 같이 작성했다고 하자면 (일부분)

```
유메노토비라 즛토 사가시츠즈케타
키미토 보쿠토노 츠나가리오 사가시테타

< 간주 부분 : 하이 x (간주 끝까지) >

Yes! 지분오 신지테 민나오 신지테
아시타가 맛테룬다요 이카나쿠챠
Yes! 요칸노 호시타치 무네니 훗테키타
카가야케…마요이나가라 타치아가루요
```

바로 렌더링 칸에 내용이 생기면서 단어끼리 뭉쳐있는 것을 볼 수 있습니다.

![image](https://user-images.githubusercontent.com/32066651/72499105-4b5d7800-3874-11ea-8239-5cab921bdbe2.png)

이 상태에서 그대로 하시게 되면 최종 결과물이

![image](https://user-images.githubusercontent.com/32066651/72499159-64662900-3874-11ea-9194-7068d4657b1f.png)

위 이미지 처럼 띄어쓰기기가 없는 상태로 되니 가사 편집기 아래에 있는 

![image](https://user-images.githubusercontent.com/32066651/72499023-1bae7000-3874-11ea-948d-917be4b3011e.png)

버튼을 누르시게 되면 다음과 같이 바뀌는 것을 알 수 있습니다.

```
유 메 노 토 비 라  즛 토  사 가 시 츠 즈 케 타
키 미 토  보 쿠 토 노  츠 나 가 리 오  사 가 시 테 타

<  간 주  부 분  :  하 이  x  ( 간 주  끝 까 지 )  >

Y e s!  지 분 오  신 지 테  민 나 오  신 지 테
아 시 타 가  맛 테 룬 다 요  이 카 나 쿠 챠
Y e s!  요 칸 노  호 시 타 치  무 네 니  훗 테 키 타
카 가 야 케 … 마 요 이 나 가 라  타 치 아 가 루 요
```

저러면 각 칸마다 띄어쓰여져 최종 결과물이 원본과 같은 형식으로 되는데
저 상태 그대로 편집하기에는 몇가지 어려운 점이 있습니다.

1. 괄호 부분 옆 단어와 붙어져 있지 않아 싱크 맞추기가 귀찮음
2. 영어 부분은 다 음절이 구분되어 있어 이 역시 싱크 맞추기가 귀찮음
3. 특수 문자들은 딱 한번만 앞 문자와 붙기 때문에 이 역시 싱크 맞추기가 귀찮음

위 사항을 감수하시겠다면 괜찮은데 이는 가사 작성 효율성이 엄청 떨어지므로 비밀 추천드립니다.

위 사항을 다듬어 다시 작성하면 아래와 같이 됩니다.

```
유 메 노 토 비 라  즛 토  사 가 시 츠 즈 케 타
키 미 토  보 쿠 토 노  츠 나 가 리 오  사 가 시 테 타

<  간주  부분  :  하이  x  (간주  끝까지)  >

Yes!  지 분 오  신 지 테  민 나 오  신 지 테
아 시 타 가  맛 테 룬 다 요  이 카 나 쿠 챠
Yes!  요 칸 노  호 시 타 치  무 네 니  훗 테 키 타
카 가 야 케… 마 요 이 나 가 라  타 치 아 가 루 요
```

그러면 위와 같이 영어 단어와 "간주 부분 : 하이 x (간주 끝까지) 부분이 편집하기 좋게 바뀜을 확인할 수 있습니다.

(다음 쓰레드에 계속 작성 예정)

**Comment by So-chiru** [comment]
이런식으로 가사를 다 작성하셨다면 작성 완료를 누르세요.
그러면 가사 탭이 사라지면서 렌더링과 속성 칸만 남게되는 것을 알 수 있습니다. (속성 칸의 텍스트 편집기 보기를 클릭해 다시 볼 수 있음.)

각 음절의 싱크를 맞추기에 앞서 아셔야 할 것은 단어의 속성입니다.
각 단어의 속성은 속성 탭에 있는 것들이 전부입니다.

![image](https://user-images.githubusercontent.com/32066651/72499670-d0955c80-3875-11ea-8d1f-c7ec3b367c6d.png)

렌더링 탭에서 단어를 선택하시게되면 단어가 빨간색으로 바뀌면서 속성 탭의 값도 바뀌게 되는데
맨 처음 단어인 "유"를 선택하시면

![image](https://user-images.githubusercontent.com/32066651/72499727-fde20a80-3875-11ea-99cf-4900b1018c0a.png)

칸이 활성화 되면서 수정 가능한 상태로 바뀌는 것을 알 수 있습니다.

선택된 단어의 줄 속성은 아직 건드실 필요는 없고 단어들의 속성들을 건드셔야하는데
이 부분을 설명해드리면

![image](https://user-images.githubusercontent.com/32066651/72499818-43063c80-3876-11ea-9abb-e102214726ae.png)

저런 식입니다.

제일 중요한 2가지는 "시작 시간", "종료 시간"입니다.

시작 시간을 통해 해당 음절이 비추기 시작할 지점을 지정하고
종료 시간을 통해 해당 음절이 비추기 끝날 지점을 지정합니다.

여기서 사용되는 숫자는 아까전에 알려드린 UI 부분에서 00:00:00 / ~~:~~:~~ [**타임코드**] 부분의 타임코드가 사용됩니다.

가사 속성에 대한 기본적인 팁은 다 드렸으니 싱크를 맞추실 차례입니다.

매번 칸을 열어서 시작 시간, 종료 시간, 기타 속성들을 수정하는 것은 엄청 비효율적이기 때문에 몇가지 단축키들을 제공합니다. 그 단축키는 아래와 같습니다.

```
S : 선택된 단어들의 시작 지점을 현재 재생 위치 포인터가 가리키는 지점으로 설정
W : 선택된 단어들의 끝 지점을 현재 재생 위치 포인터가 가리키는 지점으로 설정
P : 선택된 단어들의 발음 끝 지점을 현재 재생 위치 포인터가 가리키는 지점으로 설정 (현재 구현 안됨)
(위 3개 키) x 2 (옵션 선택시) : 기능은 각 키와 같으나 수행 후 선택된 모든 단어를 선택 해제함
Alt + (위 3개 키) : 기능은 각 키와 같으나 수행 후 가장 먼저 선택된 단어를 선택 해제함
Shift + (위 3개 키) : 기능은 각 키와 같으나 수행 후 선택된 모든 단어를 선택 해제함
[ : S + Alt 기능 (시작 지점 설정 후 선택 해제)
] : W + Alt 기능 (종료 지점 설정 후 선택 해제)

Delete : 선택된 단어를 삭제

Space : 노래 일시 정지 / 재생
좌측 방향키, Tab : 0.3초 전으로
우측 방향키 : 0.3초 후로
PageUp : 30초 전으로
PageDown: 30초 후로
Home : 노래의 처음으로
End : 노래의 끝으로
```

제가 제일 많이 사용하는 키 조합이면서 거의 유일하게 사용될 키 조합은
```
[, ], Shift + W
```
입니다.

**Comment by So-chiru** [comment]
이제 싱크를 시작해봅시다. 이 과정이 마지막인 만큼 시간을 제일 잡아먹습니다 ㅠ

여러번 싱크를 맞춰보면서 느낀점이 다음 단계로 진행하면 편하다는 것을 깨달았습니다.

1. 단어 타입 지정
2. 단어의 종료 시간 지정 (콜 제외)
3. 단어의 시작 시간 지정 (콜 제외)
4. 기타 남은 콜 같은 단어들의 싱크를 맞춤

이 순서입니다.

### 1. 단어 타입 지정 ###

사이트의 콜을 열어보시면 여러가지 색깔로 이루어져 있는 것을 알 수 있는데
단어의 타입을 지정함으로써 해당 색상으로 맞출 수 있습니다.

#### I. 가사 ####

![image](https://user-images.githubusercontent.com/32066651/72500773-9b3e3e00-3878-11ea-9b02-7a95d83b6e69.png)

말 그대로 가사입니다. 타입 값은 **1** 이고 단어를 만들면 1로 설정되어 있으니 실수로 다른 걸로 바꾸셨다가 하는 경우 말고는 수정하는 일이 없습니다.

#### II. 콜 ####

![image](https://user-images.githubusercontent.com/32066651/72500892-d93b6200-3878-11ea-91c2-c179ab7e5095.png)

우렁찬 소리를 내는 콜입니다. 타입 값은 **2** 이고 어느 때 사용되나면 **캐스트가 해당 콜을 따라 부르지 않는 경우**에 사용됩니다. 나중에 하시겠지만 콜은 주로 가사와 엇나가는 경우가 많아서 우선은 타입 지정을 해두고 **I. 가사**의 싱크를 다 맞추신 뒤에 콜의 싱크 작업을 시작하시는 편이 편합니다.

#### III. 주석 ####

![image](https://user-images.githubusercontent.com/32066651/72501055-4222da00-3879-11ea-9c22-1b26ac30e904.png)
 
얼핏보기에는 **I. 가사**와 색이 구별이 되지 않지만 미묘하게 색이 다릅니다. 타입 값은 **3** 이고 **콜의 이해를 돕는 주석을 작성할 때 사용됩니다.**

#### IV. 가사 + 콜 ####

![image](https://user-images.githubusercontent.com/32066651/72501164-7bf3e080-3879-11ea-8978-d67885a4a82b.png)

이 부분 역시 콜입니다. 타입 값은 **4** 이고 **II. 콜**과 다른 점은  **해당 부분이 가사라서 캐스트가 부르는 경우**에 사용됩니다.

**Comment by So-chiru** [comment]
### 2. 단어의 종료 시간 지정 ###

이 부분을 작업하실때는 줄 단위로 작업하시면 편합니다. 해당 줄의 처음 단어 옆에 숫자를 클릭하시면 해당 줄을 선택하실 수 있습니다.

![image](https://user-images.githubusercontent.com/32066651/72501383-f58bce80-3879-11ea-8ffa-55a79ffd7aff.png)

말 그대로 단어의 종료시간을 지정하는 부분인데 이 부분은 metadata 탭에서 재생 속도를 1.75 정도로 올리시고 작업하시면 작업 시간이 최대한 단축됩니다.

제가 추천 드리는 방식은 

1. 1.75 배로 맞추신 뒤
2. 노래를 틀어서
3. 해당 단어들의 발음이 모두 끝나면
4. Shift + W를 눌러 해당 줄의 종료 시간 지정을 한번에 끝낼 수 있습니다.

간단합니다. 이해가 안되시면 영상으로도 설명해드리겠습니다.

### 3. 단어의 시작 시간 지정 ###
위 2번 과정과 비슷합니다. 
작업하실때 0.75 배속으로 작업하시면 의외로 정확하지 않은 것 같으면서도 정확한 느낌을 준다는 것이 팁입니다.

이 과정은 해당 줄을 일단 모두 선택한 다음에 노래를 재생하면서 `[` 키를 누르면서 싱크를 맞추는 것이 편합니다.
이 과정 역시 이해가 안가시면 영상으로 설명해 드리겠습니다.

### 4. 기타 남은 콜 같은 단어들의 싱크를 맞춤 ###

말 그대로입니다. 아직 싱크가 안된 단어들을 선택하셔서 2번 3번 과정을 거치시면 됩니다.

**Comment by So-chiru** [comment]
이제 이렇게 하시면 축하드립니다 ㅠ 한 곡을 끝낸 셈이 됩니다.

이 상태에서 창을 나가면 모든 게 날라가므로 다운로드를 먼저 진행해주세요.

![image](https://user-images.githubusercontent.com/32066651/72501863-549e1300-387b-11ea-8341-c15b0b8beeca.png)

저렇게 다운로드 버튼을 누르시면 **(5자리 ID).json** 파일이 다운로드 되어집니다.

이 파일을 반디집이나 알집등 압축 프로그램을 이용하셔서 압축하시면 됩니다.

![image](https://user-images.githubusercontent.com/32066651/72501977-a2b31680-387b-11ea-90ff-9a27d872ac97.png)

그리고 Github Issue 페이지에 오셔서 https://github.com/So-chiru/LLCT/issues

![image](https://user-images.githubusercontent.com/32066651/72502050-c5452f80-387b-11ea-9d35-0e17df838f69.png)

New issue 클릭하신 후 "새 콜표 제보" 클릭하셔서 압축하신 파일을 올려주시면
제가 한번 검증을 거친 후 서버에 올립니다.
