### ISSUE TITLE
love wing bell  콜표

### ISSUE THREAD

**Issue by Lacheln1** [So-chiru/LLCT#130]
**곡명 혹은 ID**
어느 곡의 콜표를 작업 하셨는지 알려주세요.
love wing bell / 00061
**기타 내용**
관리자에게 말하고 싶은 내용이나 설명이 있다면 입력해 주세요.

**콜표 내용**
콜표 이미지나 텍스트 혹은 JSON 파일을 압축하여 올려주세요. 이미지인 경우 3232 x 2100 사이즈의 png로 올려주시면 감사하겠습니다.

[00061.zip](https://github.com/So-chiru/LLCT/files/4070249/00061.zip)

**Comment by Lacheln1** [comment]
[00061 (1).zip](https://github.com/So-chiru/LLCT/files/4070509/00061.1.zip)
공백 수정본 입니다

**Comment by So-chiru** [comment]
시간 내주셔서 수고해주셔서 감사합니다!
다음에 이 부분까지 수정하면 완성도가 높을 부분을 몇가지 알려드린다면

![image](https://user-images.githubusercontent.com/32066651/72524612-95ab1d00-38a5-11ea-95bb-3bef7993d01f.png)

영어 단어들 같은 경우는 가이드 글에서도 있듯이 병합해서 진행하면 훨씬 편합니다

![image](https://user-images.githubusercontent.com/32066651/72524699-cdb26000-38a5-11ea-9ce9-46cdef963e1d.png)

그리고 중간에 넣긴 했는데 사비 부분과 절 나뉘는 부분에서 저렇게 빈 라인을 만들어주세요!
저러면 구분이 더 쉬워집니다.

![image](https://user-images.githubusercontent.com/32066651/72525423-79a87b00-38a7-11ea-86c2-b4dd2223f3b7.png)

"미치테루**네**"
여기 부분을 가사가 끝나는 바로 그 시점에 잡아두셨는데 네~ 발음을 길게 하기 때문에 조금 뒷 부분으로 잡아두시면 좋지 않을까 생각해봅니다

처음인데 이렇게 제법 정확하게 빨리 완성해주셔서 감사합니다!
