### ISSUE TITLE
탭 비활성화 시, 콜 효과음이 들리지 않는 문제

### ISSUE THREAD

**Issue by droplet92** [So-chiru/LLCT#132]
**버그 설명**
콜표 사이트가 열려 있는 탭을 비활성화하고 있는 경우, 콜(ex. fufu) 효과음이 들리지 않음.

**재현 방법**
다음 방법을 통해 재현이 가능합니다.
1. 아무 노래나 재생
2. 해당 콜표 사이트가 열려있는 브라우저의 해당 탭을 비활성화 (ex. 노래를 켜둔 상태로 물갤 구경)
3. 콜표에서 초록색으로 된 부분의 효과음이 들리지 않음
(단, 크롬 새 창을 띄워도 해당 콜표 탭이 활성화되어 있는 상태라면 상관없음)

**원래 예상된 기능**
탭 비활성화 시에도 콜 효과음이 들릴 것.

**스크린샷**
![활성화 탭](https://user-images.githubusercontent.com/31408641/72613723-be014d00-3973-11ea-9560-14e0b55488c9.png)
탭이 활성화된 상태, 초록색 콜 부분 효과음 들을 수 있음.

![비활성화 탭](https://user-images.githubusercontent.com/31408641/72613769-e12bfc80-3973-11ea-9fc7-6e978e7f569f.png)
탭이 비활성화된 상태, 초록색 콜 부분 효과음 들을 수 없음.

**브라우저 버전:**
 - 기기: PC
 - OS: Windows 10
 - 브라우저: Chrome
 - 브라우저 버전: 79.0.3945.130(공식 빌드) (64비트)

**기타 내용**
불철주야 수고가 많으십니다.
뷰뵙 ㅎㅎ

**Comment by So-chiru** [comment]
이슈 남겨주셔서 감사합니다 ㅎㅎ

콜 틱을 불러오는 것을 requestAnimationFrame() API 를 호출해서 특정 틱마다 해당 시간에 들었는지 확인하고 소리를 내는 방식을 쓰고 있는데 백그라운드에서 requestAnimationFrame 을 쓸 경우 호출 주기가 엄청 늘어나서 결국에는 틱 소리가 수백ms 늦게 재생되는 문제가 발생합니다.

예전에는 따로 고급 옵션으로 setInterval 을 사용하는 옵션이 있었는데 그냥 백그라운드에서 콜 틱을 들으면서 외우실 분들이 별로 없을 것이라 예상 했고 백그라운드에서 틱을 살려둬도 CPU 사용량만 더 먹을 것 같기 때문에 그냥 없앴습니다 ㅜ

이 점 양해 부탁드립니다 ㅠㅠ
문제 해결 못해드려서 죄송하고 이용해주셔서 항상 감사드립니다..
