### ISSUE TITLE
콜표 오류 제보가 아니라 가사 싱크 밑에 자막뜨는건 뭔가요?

### ISSUE THREAD

**Issue by contactn** [So-chiru/LLCT#133]
니지동 콜표 보다가 새로운 자막시스템이 보이네요 ㅋㅋㅋㅋ
![자막](https://user-images.githubusercontent.com/57008083/73150066-b70ed300-4107-11ea-80d3-ac48b2280235.PNG)

**Comment by So-chiru** [comment]
맨 앞 단어 선택하시고 아래 칸 수정하시면 가사를 사용할 수 있읍니다..

![image](https://user-images.githubusercontent.com/32066651/73150091-dc9bdc80-4107-11ea-877e-6cb99ac331fa.png)

![image](https://user-images.githubusercontent.com/32066651/73150121-fe955f00-4107-11ea-8b22-ac55d53d8bd6.png)

**Comment by contactn** [comment]
아핫 물붕앜ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ
감사합니다 ㅋㅋㅋㅋㅋㅋㅋㅋ
