### ISSUE TITLE
Guilty!? Farewell party 가사 싱크 , 콜&리스폰스 표

### ISSUE THREAD

**Issue by contactn** [So-chiru/LLCT#134]
**곡명 혹은 ID**
어느 곡의 콜표를 작업 하셨는지 알려주세요.
Guilty!? Farewell party , 10063

**기타 내용**
관리자에게 말하고 싶은 내용이나 설명이 있다면 입력해 주세요.

**콜표 내용**
콜표 이미지나 텍스트 혹은 JSON 파일을 압축하여 올려주세요. 이미지인 경우 3232 x 2100 사이즈의 png로 올려주시면 감사하겠습니다.
[10063.zip](https://github.com/So-chiru/LLCT/files/4115737/10063.zip)

**Comment by So-chiru** [comment]
콜표 작업 감사합니다! 이제 당분간은 사이트 리뉴얼 작업 때문에 콜표 올라가는게 늦어질 수 있습니다.. 그러니 완전 할꺼 없으실 때 작업 해주시면 감사하겠습니다..

![image](https://user-images.githubusercontent.com/32066651/73170931-eee73c00-4142-11ea-8ad2-aebaa283644e.png)

**Comment by contactn** [comment]
리뉴얼이라니.. 힘든작업 간바루비입니다!
