### ISSUE TITLE
어.. 혹시 콜표제작 주소 바꼇나요?

### ISSUE THREAD

**Issue by contactn** [So-chiru/LLCT#138]
**잘못된 곡명 (콜표)**
여기에 잘못된 콜이 있는 곡의 곡의 이름이나 ID를 적어주세요.

**오류 내용**
오류 내용을 자세히 적어 주시면 빠른 파악 및 해결이 가능합니다.
https://lovelivec.kr/editor.html?id= 이 주소로 들어갔는데 안들어가지네요.
**추가 내용 (이미지)**
스크린샷이나 이미지가 있다면 여기에 올려주세요.
![오류인가요](https://user-images.githubusercontent.com/57008083/74149643-96886200-4c4b-11ea-99c6-0ec18449a93e.PNG)

**Comment by So-chiru** [comment]
새 페이지에 에디터를 구현하지 않아서
https://old.lovelivec.kr/editor.html?id=

로 들어가시면 사용 가능합니다

**Comment by contactn** [comment]
아하 알겠습니다
