### ISSUE TITLE
近未来ハッピーエンド 가사 싱크 , 콜&리스폰스 표

### ISSUE THREAD

**Issue by contactn** [So-chiru/LLCT#139]
**곡명 혹은 ID**
어느 곡의 콜표를 작업 하셨는지 알려주세요.
近未来ハッピーエンド , 10049
**기타 내용**
관리자에게 말하고 싶은 내용이나 설명이 있다면 입력해 주세요.

**콜표 내용**
콜표 이미지나 텍스트 혹은 JSON 파일을 압축하여 올려주세요. 이미지인 경우 3232 x 2100 사이즈의 png로 올려주시면 감사하겠습니다.
[10049.zip](https://github.com/So-chiru/LLCT/files/4181534/10049.zip)

**Comment by So-chiru** [comment]
![call](https://user-images.githubusercontent.com/32066651/74163344-99904c00-4c65-11ea-9ee8-050a111a9bee.png)

수고 하셨습니다! 근데 유닛 곡에는 색상 표시를 안넣는 편이 더 나을 것 같습니다 ㅠ
이미지 콜표 같은 경우 특히 색이 많아서 해야 할 콜과의 시인성이 떨어지는 부분이 있네요

**Comment by So-chiru** [comment]
![call](https://user-images.githubusercontent.com/32066651/74163786-3b179d80-4c66-11ea-8bd7-3e9f664ba5ec.png)

**Comment by contactn** [comment]
네 알겠습니다
