### ISSUE TITLE
오타

### ISSUE THREAD

**Issue by 616659** [So-chiru/LLCT#140]
사이트 잘 쓰고 있습니다만 오타가 몇몇 보이네요. 

Guilty Night, **Gulity** Kiss,  New **Romatic** Sailors 이렇게 두개 오타 있습니다. 뮤즈랑 니지동은 잘 모르겠네요

그리고 그냥 궁금해서 물어보는겁니다만, old.lovelivec.kr은 이 사이트와 함께 계속 유지하실건가요? 

늘 수고하시고 감사합니다.

**Comment by So-chiru** [comment]
해당 부분은 수정 했습니다 🍊

> 그리고 그냥 궁금해서 물어보는겁니다만, old.lovelivec.kr은 이 사이트와 함께 계속 유지하실건가요?

새로 디자인한 사이트에서는 에디터 구현 (https://old.lovelivec.kr/editor.html?id=) 을 구현 해두지 않아서 따로 old.lovelivec.kr 로 작업을 할 수 있게끔 해뒀는데, 새로 디자인한 사이트에서 에디터 구현이 완료되면 lovelivec.kr 단독으로 사용할 예정입니다
