### ISSUE TITLE
가사 등록하셨다고 올리셨는데 가사가 안보여요..

### ISSUE THREAD

**Issue by contactn** [So-chiru/LLCT#155]
**버그 설명**
버그를 정확히 설명 해 주시면 빠른 파악이 가능합니다.
어디에 올리신건가요??
**재현 방법**
다음 방법을 통해 재현이 가능합니다.
1. '...' 아이콘 클릭
2. '...' 버튼 클릭
3. 버그 발견

**원래 예상된 기능**
버그가 없었다면 원래 보여질 기능에 대해서 아시면 설명 해주세요.

**스크린샷**
스크린샷이 있다면 올려주세요.

**브라우저 버전:**
 - 기기: [예시: iPhone XS Max, PC]
 - OS: [예시: iOS13.0, Windows 10]
 - 브라우저 [예시: Chrome, Safari]
 - 브라우저 버전 [예시: 13 (Safari인 경우 OS 버전)]

**기타 내용**
기타 내용이 있다면 적어주세요.

**Comment by So-chiru** [comment]
새로 디자인된 사이트에서는 이 repository가 아니라 다른 비공개 repo에 저장됩니다

![image](https://user-images.githubusercontent.com/32066651/75089010-b860dd80-5597-11ea-9afa-dfe102a03dc1.png)


https://api.lovelivec.kr/call/10001

**Comment by contactn** [comment]
어.. 잘 모르겟네요;; 다뤄본적이 없어서.. ㅎㅎ
