### ISSUE TITLE
API 서버 오류?

### ISSUE THREAD

**Issue by 616659** [So-chiru/LLCT#158]
한 분이 사이트가 이상하다고 해서 저도 들어가보니 똑같이 오류가 뜨길래 작성합니다. 

우선 오류 메세지는 "API 서버에 연결할 수 없습니다. undefined"라고 뜨고, 사이트 기본 틀만 로딩이 되고 곡이 뜨질 않네요. 어제 커밋하셨던데 이 커밋에서 문제가 발생하지 않았나 생각합니다. 직접 뭐가 문제인지 보려고도 했지만 뭐가 뭔지 못 알아먹겠어서 도와드릴수는 없네요 ㅋㅋ

**Comment by So-chiru** [comment]
단순한 서버 오류였습니다. 알려주셔서 감사합니다.. ^^
