### ISSUE TITLE
콜표 건의 솔로곡

### ISSUE THREAD

**Issue by dbehd** [So-chiru/LLCT#98]
![치카 솔로](https://user-images.githubusercontent.com/50983230/58424479-70795c80-80d2-11e9-9e35-7a81b7ad9029.jpg)

![하나마루 솔로](https://user-images.githubusercontent.com/50983230/58424489-766f3d80-80d2-11e9-8644-571ee274b899.jpg)

![요시코 솔로](https://user-images.githubusercontent.com/50983230/58424497-7a9b5b00-80d2-11e9-905a-3cfbced8c294.jpg)

![리코 솔로](https://user-images.githubusercontent.com/50983230/58424504-7cfdb500-80d2-11e9-9538-4ba679672517.jpg)

![요우 솔로](https://user-images.githubusercontent.com/50983230/58424511-825aff80-80d2-11e9-9331-10b95c0f9914.jpg)

![루비 솔로](https://user-images.githubusercontent.com/50983230/58424519-86871d00-80d2-11e9-8059-dcefafd9d102.jpg)

![다이아 솔로](https://user-images.githubusercontent.com/50983230/58424527-89820d80-80d2-11e9-8fb0-d238174a8235.jpg)

![마리 솔로](https://user-images.githubusercontent.com/50983230/58424543-93a40c00-80d2-11e9-9786-7604ff5de541.jpg)

![카난 솔로](https://user-images.githubusercontent.com/50983230/58424548-97d02980-80d2-11e9-9c7e-0b1cc8d5d132.jpg)

**Comment by So-chiru** [comment]
### 모든 솔로 곡은 메타 (색상) 작업 필요.

- [ ] One more sunshine story (10071)
- [ ] 안녕히 주무세여러분 (10072)
- [ ] In this unstable world (10073) - call 2ln (masking d/ 1ln)
- [ ] Pianoforte Monologue (10074)
- [ ] Beginner’s Sailing (10075) - call 2ln
- [ ] RED GEM WINK (10076)
- [ ] WHITE FIRST LOVE (10077)
- [ ] New winding road (10078)
- [ ] SAKANAN (10079)
